name: Build Docker Images for Multi-Arch

on:
  push:
    branches:
      - branchHTTPserver

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for ${{ matrix.architecture }}
        run: |
          docker buildx create --use
          echo "Building image for linux/${{ matrix.architecture }}..."
          docker buildx build \
            --platform linux/${{ matrix.architecture }} \
            -t sommeonne/http_server:${{ matrix.architecture }} \
            --push .
