name: Build Docker Image for Multi-Arch

on:
  push:
    branches:
      - branchHTTPserver

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image for ${{ matrix.architecture }}
        run: |
          docker buildx create --use
          echo "Building and pushing image for linux/${{ matrix.architecture }}..."
          docker buildx build \
            --platform linux/${{ matrix.architecture }} \
            --load \
            -t sommeonnee/http_server:${{ matrix.architecture }} \
            .

          docker push sommeonnee/http_server:${{ matrix.architecture }}

  create-manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push Docker manifest with 'manifest' tag
        run: |
          echo "Creating multi-arch manifest..."
          docker manifest create sommeonnee/http_server:manifest \
            sommeonnee/http_server:amd64 \
            sommeonnee/http_server:arm64

          docker manifest annotate sommeonnee/http_server:manifest sommeonnee/http_server:amd64 --os linux --arch amd64
          docker manifest annotate sommeonnee/http_server:manifest sommeonnee/http_server:arm64 --os linux --arch arm64

          docker manifest push sommeonnee/http_server:manifest
